/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MPHpages;

/**
 *
 * @author Dell
 */
public class PayrollPage extends javax.swing.JFrame {

    /**
     * Creates new form PayrollPage
     */
    public PayrollPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payrollmainPNL = new javax.swing.JPanel();
        payrollheaderPNL = new javax.swing.JPanel();
        payrollheaderLBL = new javax.swing.JLabel();
        backbuttonattendancePB = new javax.swing.JButton();
        payrollscrollSP = new javax.swing.JScrollPane();
        payrollareaTA = new javax.swing.JTextArea();
        payrollemployeeidLBL = new javax.swing.JLabel();
        inputidpayLBL = new javax.swing.JLabel();
        payrollfirstnameLBL = new javax.swing.JLabel();
        inputfirstnamepayLBL = new javax.swing.JLabel();
        payrolllastnameLBL = new javax.swing.JLabel();
        inputlastnamepayLBL = new javax.swing.JLabel();
        payrollpositionLBL = new javax.swing.JLabel();
        inputpositionpayLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        payrollmainPNL.setBackground(new java.awt.Color(204, 204, 204));

        payrollheaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        payrollheaderLBL.setText("Payroll Information");

        backbuttonattendancePB.setBackground(new java.awt.Color(204, 0, 0));
        backbuttonattendancePB.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        backbuttonattendancePB.setText("Back");
        backbuttonattendancePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonattendancePBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout payrollheaderPNLLayout = new javax.swing.GroupLayout(payrollheaderPNL);
        payrollheaderPNL.setLayout(payrollheaderPNLLayout);
        payrollheaderPNLLayout.setHorizontalGroup(
            payrollheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, payrollheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbuttonattendancePB, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payrollheaderLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
        );
        payrollheaderPNLLayout.setVerticalGroup(
            payrollheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payrollheaderPNLLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(payrollheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backbuttonattendancePB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payrollheaderLBL))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        payrollareaTA.setBackground(new java.awt.Color(153, 153, 153));
        payrollareaTA.setColumns(20);
        payrollareaTA.setRows(5);
        payrollscrollSP.setViewportView(payrollareaTA);

        payrollemployeeidLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payrollemployeeidLBL.setForeground(new java.awt.Color(0, 0, 0));
        payrollemployeeidLBL.setText("Employee ID:");

        inputidpayLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        inputidpayLBL.setForeground(new java.awt.Color(0, 0, 0));
        inputidpayLBL.setText(". . .");

        payrollfirstnameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payrollfirstnameLBL.setForeground(new java.awt.Color(0, 0, 0));
        payrollfirstnameLBL.setText("First Name:");

        inputfirstnamepayLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        inputfirstnamepayLBL.setForeground(new java.awt.Color(0, 0, 0));
        inputfirstnamepayLBL.setText(". . .");

        payrolllastnameLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payrolllastnameLBL.setForeground(new java.awt.Color(0, 0, 0));
        payrolllastnameLBL.setText("Last Name:");

        inputlastnamepayLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        inputlastnamepayLBL.setForeground(new java.awt.Color(0, 0, 0));
        inputlastnamepayLBL.setText(". . .");

        payrollpositionLBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        payrollpositionLBL.setForeground(new java.awt.Color(0, 0, 0));
        payrollpositionLBL.setText("Position:");

        inputpositionpayLBL.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        inputpositionpayLBL.setForeground(new java.awt.Color(0, 0, 0));
        inputpositionpayLBL.setText(". . .");

        javax.swing.GroupLayout payrollmainPNLLayout = new javax.swing.GroupLayout(payrollmainPNL);
        payrollmainPNL.setLayout(payrollmainPNLLayout);
        payrollmainPNLLayout.setHorizontalGroup(
            payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(payrollheaderPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(payrollmainPNLLayout.createSequentialGroup()
                .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payrollmainPNLLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(payrollfirstnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payrolllastnameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payrollemployeeidLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(payrollmainPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(payrollpositionLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputidpayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputlastnamepayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputfirstnamepayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputpositionpayLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(payrollscrollSP, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        payrollmainPNLLayout.setVerticalGroup(
            payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payrollmainPNLLayout.createSequentialGroup()
                .addComponent(payrollheaderPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payrollmainPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(payrollscrollSP)
                        .addContainerGap())
                    .addGroup(payrollmainPNLLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payrollemployeeidLBL)
                            .addComponent(inputidpayLBL))
                        .addGap(18, 18, 18)
                        .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payrollfirstnameLBL)
                            .addComponent(inputfirstnamepayLBL))
                        .addGap(18, 18, 18)
                        .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payrolllastnameLBL)
                            .addComponent(inputlastnamepayLBL))
                        .addGap(18, 18, 18)
                        .addGroup(payrollmainPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(payrollpositionLBL)
                            .addComponent(inputpositionpayLBL))
                        .addContainerGap(301, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(payrollmainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(payrollmainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonattendancePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonattendancePBActionPerformed

        // Create an instance of EmployeePage
        EmployeePage employeePage = new EmployeePage();
        // Center the EmployeePage
        employeePage.setLocationRelativeTo(null);
        // Make the EmployeePage visible
        employeePage.setVisible(true);
        // Close the current AboutPage
        this.dispose();
    }//GEN-LAST:event_backbuttonattendancePBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayrollPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayrollPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayrollPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayrollPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayrollPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbuttonattendancePB;
    private javax.swing.JLabel inputfirstnamepayLBL;
    private javax.swing.JLabel inputidpayLBL;
    private javax.swing.JLabel inputlastnamepayLBL;
    private javax.swing.JLabel inputpositionpayLBL;
    private javax.swing.JTextArea payrollareaTA;
    private javax.swing.JLabel payrollemployeeidLBL;
    private javax.swing.JLabel payrollfirstnameLBL;
    private javax.swing.JLabel payrollheaderLBL;
    private javax.swing.JPanel payrollheaderPNL;
    private javax.swing.JLabel payrolllastnameLBL;
    private javax.swing.JPanel payrollmainPNL;
    private javax.swing.JLabel payrollpositionLBL;
    private javax.swing.JScrollPane payrollscrollSP;
    // End of variables declaration//GEN-END:variables
}
